### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by signalworker123** [xiaobaicxy/GAN-MNIST-Pytorch#1]
Expected all tensors to be on the same device, but found at least two device.将代码运行的报错，设置的GPU但是还是有张量在cpu里这是怎么回事？

**Comment by xiaobaicxy** [comment]
> Expected all tensors to be on the same device, but found at least two device.将代码运行的报错，设置的GPU但是还是有张量在cpu里这是怎么回事？
你好，模型没有部署到gpu上，将79、80行修改为如下：
D = D(image_size, hidden_size).to(device)
G = G(latent_size, hidden_size, image_size).to(device)

**Comment by signalworker123** [comment]
谢谢你，问题解决了。但是又有一个问题就是我把代码跑了两边都没有显示手写字的图片。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaobaicxy/GAN-MNIST-Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaobaicxy/GAN-MNIST-Pytorch] Bug (Issue #1)





  
Expected all tensors to be on the same device, but found at least two device.将代码运行的报错，设置的GPU但是还是有张量在cpu里这是怎么回事？
 你好，模型没有部署到gpu上，将79、80行修改为如下：
 D = D(image_size, hidden_size).to(device)
 G = G(latent_size, hidden_size, image_size).to(device)
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaobaicxy** [comment]
> 谢谢你，问题解决了。但是又有一个问题就是我把代码跑了两边都没有显示手写字的图片。
> […](#)

最后加一个plt.show()（实在抱歉，之前提交前不小心删到了）

**Comment by signalworker123** [comment]
非常感谢

**Comment by signalworker123** [comment]
你好，我把代码成功的跑了一遍，观察生成图片的变化，但是感觉生成的图片不是很像手写数字，而且跑一遍代码要1个小时左右，我想请问下你，你跑的时候也是这样吗？
这是我生成手写数字的变化
第一次
(https://user-images.githubusercontent.com/92248253/140714007-5dda4a2d-c628-48cf-8816-c824e32838fc.png)
最后一次
(https://user-images.githubusercontent.com/92248253/140714301-215afc07-ad97-4f3e-b8c0-563f5c0914c0.png)
中间的其他结果省略了

**Comment by xiaobaicxy** [comment]
> 你好，我把代码成功的跑了一遍，观察生成图片的变化，但是感觉生成的图片不是很像手写数字，而且跑一遍代码要1个小时左右，我想请问下你，你跑的时候也是这样吗？ 这是我生成手写数字的变化 第一次 (https://user-images.githubusercontent.com/92248253/140714007-5dda4a2d-c628-48cf-8816-c824e32838fc.png) 最后一次 (https://user-images.githubusercontent.com/92248253/140714301-215afc07-ad97-4f3e-b8c0-563f5c0914c0.png) 中间的其他结果省略了

你好，我生成的图片感觉还可以。你可以尝试调节一下生成器与判别器的优化比例，比如生成器每个epoch都优化，判别器每两个epoch才优化一次等。下图是我生成的图片。
![Figure_1](https://user-images.githubusercontent.com/37175062/142809022-ea09eb17-04de-437c-a0af-7969424a73d1.png)
